### ISSUE TITLE
exec('which drush') fails on drush init()

### ISSUE THREAD

**Issue by jeson114** [elliotttf/drush-node#4] opened 2017-08-16 07:41 UTC
unable to run the command and i get a failure on 'which drush' . examining the source i found that which drush is executed by a child process . What does the command 'which drush' do ?

**Comment by elliotttf** [comment] 2017-08-18 20:52
This locates the path to the drush executable. If you don't have `which` available though that will cause an error. I believe this is a duplicate of #3.

**Closed as completed by elliotttf** 2017-08-18 20:52 UTC

**Comment by jeson114** [comment] 2017-09-05 06:57
Yea , Thanks that fixed it
